version: 2

workflows:
  version: 2
  dist-compile:
    jobs:
      - compile



jobs:
  compile:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: apt update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*
      - run: sudo apt update && sudo apt-get install -y gcc g++
      - run: apt-get install -y wget
      - run: wget https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2.tar.gz
      - run: tar -zxvf cmake-3.15.2.tar.gz
      - run: apt-get install -y build-essential
      - run: cd cmake-3.15.2 && ./bootstrap && make && sudo make install
      - run: sudo apt update && sudo apt-get install -y cppcheck
      - run: sudo apt update && sudo apt-get install -y valgrind
      - run: cd ~/project/
      - run: chmod +x build_test.sh
      - run: ./build_test.sh && valgrind build/Test
